make: cpsc2150/extendedTicTacToe/GameScreen.java cpsc2150/extendedTicTacToe/models/IGameBoard.java cpsc2150/extendedTicTacToe/models/BoardPosition.java cpsc2150/extendedTicTacToe/models/GameBoard.java cpsc2150/extendedTicTacToe/models/AbsGameBoard.java
	javac cpsc2150/extendedTicTacToe/GameScreen.java cpsc2150/extendedTicTacToe/models/IGameBoard.java cpsc2150/extendedTicTacToe/models/BoardPosition.java cpsc2150/extendedTicTacToe/models/GameBoard.java cpsc2150/extendedTicTacToe/models/AbsGameBoard.java

make run: cpsc2150/.extendedTicTacToe.models.BoardPosition.class cpsc2150/.extendedTicTacToe.models.GameBoard.class cpsc2150/.extendedTicTacToe.models.AbsGameBoard.class cpsc2150.extendedTicTacToe.GameScreen.class
	java cpsc2150.extendedTicTacToe.GameScreen

make clean:
	rm -f cpsc2150/extendedTicTacToe/*.class cpsc2150/extendedTicTacToe/models/*.class cpsc2150/extendedTicTacToe/*.interface